name: Deploy

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6
      - name: Build lambda zip
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/${{ secrets.APP_NAME }} ./cmd
          cd build && zip ${{ secrets.APP_NAME }}.zip ${{ secrets.APP_NAME }} && cd ..
      - name: Terraform Init
        run: terraform -chdir=infra init
      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve
