name: Deploy Lambda

on:
  workflow_dispatch:
  push:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: eu-west-2
      - name: Build lambda zip
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/bootstrap ./cmd
          cd build && zip preflight.zip bootstrap && cd ..
      - name: Update Lambda code
        run: aws lambda update-function-code --function-name preflight-api --zip-file fileb://build/preflight.zip
