name: Deploy Infra

on:
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: eu-west-2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6
      - name: Build lambda zip
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/bootstrap ./cmd
          cd build && zip preflight-api.zip bootstrap && cd ..
      - name: Terraform Init
        run: terraform -chdir=infra init -backend-config="bucket=${STATE_BUCKET}" -backend-config="key=preflight-api/terraform.tfstate" -backend-config="region=eu-west-2"
        env:
          STATE_BUCKET: ${{ secrets.STATE_BUCKET }}
      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve
